import { PrismaClient, PaymentMethod, ShippingMethod, OrderStatus, User } from '@prisma/client';
import * as bcrypt from 'bcrypt';

const prisma = new PrismaClient();

const SEED_NOTE = '[SEED_STATS]';
const SEED_VISIT_PATH = '/__seed_stats__';
const RANGE_START = '2026-07-27';
const RANGE_END = '2026-09-20';
const DATA_END = '2026-08-13';

function dateRange(startStr: string, endStr: string): string[] {
  const dates: string[] = [];
  const [sy, sm, sd] = startStr.split('-').map(Number);
  const [ey, em, ed] = endStr.split('-').map(Number);
  const start = new Date(Date.UTC(sy, sm - 1, sd));
  const end = new Date(Date.UTC(ey, em - 1, ed));

  for (const date = new Date(start); date <= end; date.setUTCDate(date.getUTCDate() + 1)) {
    dates.push(date.toISOString().slice(0, 10));
  }
  return dates;
}

function dateValue(date: string): Date {
  return new Date(`${date}T00:00:00.000Z`);
}

/** Create an instant at a chosen Vietnam local time. */
function vietnamDateTime(date: string, hour: number, minute = 0): Date {
  return new Date(`${date}T${String(hour).padStart(2, '0')}:${String(minute).padStart(2, '0')}:00+07:00`);
}

async function seedCakes() {
  const dauXanh = await prisma.cake.upsert({
    where: { kind: 'Dau Xanh' },
    update: {},
    create: {
      kind: 'Dau Xanh',
      description: 'Bánh đậu xanh thơm béo',
      basePrice: 70000,
    },
  });

  const sauRieng = await prisma.cake.upsert({
    where: { kind: 'Sau Rieng' },
    update: {},
    create: {
      kind: 'Sau Rieng',
      description: 'Bánh sầu riêng đậm vị',
      basePrice: 85000,
    },
  });

  return [dauXanh, sauRieng];
}

async function seedAdmin() {
  const passwordHash = await bcrypt.hash('123', 10);
  await prisma.admin.upsert({
    where: { username: 'loan' },
    update: {},
    create: { username: 'loan', fullName: 'Loan', passwordHash },
  });
}

async function seedUsers(): Promise<User[]> {
  const users: User[] = [];

  // Returning users: registered before the selected statistics range.
  for (let i = 1; i <= 8; i++) {
    users.push(await prisma.user.upsert({
      where: { phone: `09990000${String(i).padStart(2, '0')}` },
      update: {},
      create: {
        phone: `09990000${String(i).padStart(2, '0')}`,
        fullName: `Khách cũ ${i}`,
        createdAt: vietnamDateTime('2026-07-01', 9 + (i % 3)),
      },
    }));
  }

  // New users: registered during the selected range.
  for (let i = 1; i <= 4; i++) {
    users.push(await prisma.user.upsert({
      where: { phone: `09991000${String(i).padStart(2, '0')}` },
      update: {},
      create: {
        phone: `09991000${String(i).padStart(2, '0')}`,
        fullName: `Khách mới ${i}`,
        createdAt: vietnamDateTime(`2026-08-0${i + 1}`, 10),
      },
    }));
  }

  return users;
}

async function seedAvailability(cakes: Awaited<ReturnType<typeof seedCakes>>) {
  let created = 0;
  for (const cake of cakes) {
    for (const date of dateRange(RANGE_START, RANGE_END)) {
      const result = await prisma.availability.upsert({
        where: { cakeId_date: { cakeId: cake.id, date: dateValue(date) } },
        update: {},
        create: {
          cakeId: cake.id,
          date: dateValue(date),
          maxCapacity: 50,
          bufferLimit: 52,
          currentBooked: 0,
        },
      });
      if (result) created++;
    }
  }
  return created;
}

async function seedCompletedOrders(
  cakes: Awaited<ReturnType<typeof seedCakes>>,
  users: Awaited<ReturnType<typeof seedUsers>>,
) {
  // Only remove data generated by this seed, never real application data.
  await prisma.order.deleteMany({ where: { note: { startsWith: SEED_NOTE } } });

  let created = 0;
  for (const [dayIndex, date] of dateRange(RANGE_START, DATA_END).entries()) {
    // 1..4 completed orders/day creates visible variation in charts.
    const orderCount = 1 + (dayIndex % 4);

    for (let orderIndex = 0; orderIndex < orderCount; orderIndex++) {
      const user = users[(dayIndex * 3 + orderIndex) % users.length];
      const firstCake = cakes[(dayIndex + orderIndex) % cakes.length];
      const secondCake = cakes[(dayIndex + orderIndex + 1) % cakes.length];
      const firstQuantity = 1 + ((dayIndex + orderIndex) % 3);
      const secondQuantity = orderIndex % 2 === 0 ? 1 : 0;
      const firstEggCount = (dayIndex + orderIndex) % 4;
      const secondEggCount = (firstEggCount + 1) % 4;

      const items = [
        {
          cakeId: firstCake.id,
          quantity: firstQuantity,
          eggCount: firstEggCount,
          priceAtPurchase: firstCake.basePrice,
        },
        ...(secondQuantity > 0
          ? [{
              cakeId: secondCake.id,
              quantity: secondQuantity,
              eggCount: secondEggCount,
              priceAtPurchase: secondCake.basePrice,
            }]
          : []),
      ];

      const totalMoney = items.reduce(
        (sum, item) => sum + Number(item.priceAtPurchase) * item.quantity,
        0,
      );

      await prisma.order.create({
        data: {
          userId: user.id,
          totalMoney,
          note: `${SEED_NOTE} ${date} order-${orderIndex + 1}`,
          orderDate: vietnamDateTime(date, 8 + ((orderIndex + dayIndex) % 10)),
          receiveDate: dateValue(date),
          shippingMethod: orderIndex % 2 === 0 ? ShippingMethod.PICKUP : ShippingMethod.DELIVERY,
          paymentMethod: orderIndex % 2 === 0 ? PaymentMethod.CASH : PaymentMethod.BANK_TRANSFER,
          status: OrderStatus.COMPLETED,
          items: { create: items },
        },
      });
      created++;
    }
  }
  return created;
}

async function seedVisitLogs(users: Awaited<ReturnType<typeof seedUsers>>) {
  await prisma.visitLog.deleteMany({ where: { path: SEED_VISIT_PATH } });

  let created = 0;
  for (const [dayIndex, date] of dateRange(RANGE_START, DATA_END).entries()) {
    // Anonymous visits are included so total visits is larger than known users.
    const anonymousVisits = 10 + (dayIndex % 6);
    for (let i = 0; i < anonymousVisits; i++) {
      const deviceType = i % 10 < 6 ? 'mobile' : i % 10 < 9 ? 'desktop' : 'other';
      await prisma.visitLog.create({
        data: {
          userId: null,
          deviceType,
          userAgent: deviceType === 'mobile' ? 'Seed Mobile UA' : 'Seed Desktop UA',
          path: SEED_VISIT_PATH,
          createdAt: vietnamDateTime(date, 8 + (i % 12), i % 60),
        },
      });
      created++;
    }

    // Known users produce returning/new visitor values for the visitor chart.
    const knownVisitCount = 3 + (dayIndex % 5);
    for (let i = 0; i < knownVisitCount; i++) {
      const user = users[(dayIndex + i) % users.length];
      const deviceType = i % 3 === 0 ? 'desktop' : 'mobile';
      await prisma.visitLog.create({
        data: {
          userId: user.id,
          deviceType,
          userAgent: deviceType === 'mobile' ? 'Seed Known Mobile UA' : 'Seed Known Desktop UA',
          path: SEED_VISIT_PATH,
          createdAt: vietnamDateTime(date, 9 + (i % 8), (i * 7) % 60),
        },
      });
      created++;
    }
  }
  return created;
}

async function main() {
  const cakes = await seedCakes();
  await seedAdmin();
  const users = await seedUsers();
  const slotsCreated = await seedAvailability(cakes);
  const ordersCreated = await seedCompletedOrders(cakes, users);
  const visitsCreated = await seedVisitLogs(users);

  console.log(
    `Seed done ✓ — data range ${RANGE_START} → ${DATA_END}; ` +
      `availability through ${RANGE_END}; ` +
      `${slotsCreated} slots, ${ordersCreated} completed orders, ${visitsCreated} visits`,
  );
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
