import type { Metadata } from "next";
import { Be_Vietnam_Pro, Vollkorn } from "next/font/google"; 
import "./globals.css";

const beVietnamPro = Be_Vietnam_Pro({
  weight: ["400", "500", "700"],
  subsets: ["vietnamese"], 
  variable: "--font-be-vietnam",
});

const vollkorn = Vollkorn({
  weight: ["400", "600", "700"],
  subsets: ["vietnamese"],
  variable: "--font-vollkorn",
});

export const metadata: Metadata = {
  title: "Bánh Tròn Vị Ngọt",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="vi"
      className={`${beVietnamPro.variable} ${vollkorn.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="font-sans min-h-full flex flex-col">
        {children}
      </body>
    </html>
  );
}