services:
  postgres-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis-cache:
    image: redis:7-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
  nestjs-app:
    build: ./backend
    ports:
      - "3001:3001"
    restart: unless-stopped
    environment:
      PORT: 3001
      DATABASE_URL: ${DATABASE_URL}
      REDIS_HOST: "redis-cache"
      REDIS_PORT: 6379
      JWT_AT_SECRET: ${JWT_AT_SECRET}
      JWT_RT_SECRET: ${JWT_RT_SECRET}
    depends_on:
      postgres-db:
        condition: service_healthy
      redis-cache: 
        condition: service_healthy
volumes:
  postgres_data: